### ISSUE TITLE
Manche Links funktionieren nicht

### ISSUE THREAD

**Issue by vovinhd** [envrioomate/pwa#1]
Der Link http://https//www.haus.de/leben/trend-zero-waste-tipps-wie-sie-muell-reduzieren-und-dabei-geld-sparen in der akutellen Wochenchallenge "Lebensmittel" führt nicht zu einer Website/scheint einen Fehler zu enthalten

**Comment by tillmo** [comment]
Das liegt vermutlich nur am fehlenden Doppelpunkt nach dem `https`.

**Comment by vovinhd** [comment]
#602a5b07546692d565d00090eb3e1ba7ee557c93
